"""message

Revision ID: 6eaf4ea20311
Revises: e5ce1c32d085
Create Date: 2019-03-14 11:59:45.204007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eaf4ea20311'
down_revision = 'e5ce1c32d085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_message_timestamp'), 'message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_timestamp'), table_name='message')
    op.drop_column('message', 'timestamp')
    # ### end Alembic commands ###
